### ISSUE TITLE
Windows Compilation Help

### ISSUE THREAD

**Issue by cfholbert** [sakov/nn-c#10]
Looking for some help compiling for Windows 10. I compiled it in Linux with no problems but am struggling to get a version working in Windows using mingw64 and msys2. The command line utility nnbathy compiled and runs but does not perform the interpolation. The compiled code for the minimal ellipse construction works. When compiling, there were a few warnings about redefining "isnan." Any guidance would be very much appreciated.

**Comment by sarapierson234** [comment]
Hello there,

Thank you for your interest and question!
I do apologize, this was meant to be a private repository until the
official publish date along with my thesis work. Please feel free to check
back in the future for public work--it should be in approximately 2 or 3
months!
I also can not speak to functionality on windows, I only use GNU Radio on
Linux.

What is the functionality that you are trying to achieve/what is the
project goal that you are working on? I could possibly point you to other
helpful code.

Best,

*Sara Pierson*
BS Aerospace Engineering
PhD student | Ocean Science & Engineering
Planetary Habitability and Technology Lab
Georgia Institute of Technology

**Comment by cfholbert** [comment]
Hi Sara. I identified and fixed the problem. The code in triangle.c assumes that that triangles are four-byte-aligned and that the "unsigned long" type is long enough to hold a pointer. Unsigned long cannot be the type of the pointer in x64 so I changed it to unsigned long long.

Thank you for offering to help, but this fixed the issue and now the code works fine on Windows.
