### ISSUE TITLE
Segmentation faults in triangle.c on windows 10 64 bit

### ISSUE THREAD

**Issue by toke500** [sakov/nn-c#6]
I am using nn-c on Windows 10 64bit.

When I have big point clouds I get segmentation faults.

The problem is that a long on linux is 64bit but 32bit on windows.

I solved the problem by replacing all longs with long long in triangle.c.

The problem might occur in other parts of the code that I am not using.

I thought that others might find this useful.

**Comment by sakov** [comment]
Thanks for reporting this -- it is good to know what to look at first when the overflow happens. But so far this is the only report on this problem (in 15+ years)... Because I would rather leave triangle.c alone, I close the issue for now.
